---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14.6

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: elk-in-a-box-tests::default
    attributes:
  - name: simple-example
    run_list: elk-in-a-box-simple-example::default
    attributes:
