---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14.6

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["forwarded_port", {guest: 5601, host: 5601}]
      - ["forwarded_port", {guest: 9200, host: 9200}]
suites:
  - name: default
    run_list: elk-in-a-box::default
    attributes:
